### ISSUE TITLE
Cambio en 1er Parrafo

### ISSUE THREAD

**Issue by xombra** [cslve/gobiernoabierto#11]
En su sentido más básico, gobierno abierto es la noción de que los ciudadanos tengan la potestad de vigilar y escudriñar el accionar de los órganos de la Administración Pública a través del acceso a sus documentos y procedimientos. Este principio, considerado esencial para el correcto funcionamiento de la democracia, es comúnmente aceptado y protegido por las constituciones de casi todos los países democráticos del mundo.

Cambiar "pueblo" por "ciudadanos" y "escrutinizar"  por escudriña

**Comment by ghostbar** [comment]
Abrí un PR, porfa, las discusiones por allá.
